BaseURL = "https://kmhinstitute.com"
  languageCode = "en-us"
  title = "Dr. Kamakshi Institute of Medical Science and Research"
  theme = "samhugobs5theme"
  relativeURLS = true
  publishDir = "docs"
  
  [permalinks]
    services = ":title/"

  [params]
    author = "Zigma Marketing"
    description = "The Dr. Kamakshi Institute of Medical Sciences & Research (KIMSR) was established in the year 2010 by Dr.T.G.Govindarajan with a vision of generating required human resources for the healthcare industry. It is a unique academic institution that is committed to academic excellence. The institute is an additional facility of Dr. Kamakshi Memorial Hospital Pvt. Ltd., founded in 2005, with a vision “to serve and deliver every patient with the ultimate excellence and devotion, as we care for our loved ones”. The hospital is a 300 bedded Multi Super Specialty hospital at Pallikaranai, situated in the southern part of Chennai, spread over 60 ground land and 75000 square ft building area."
    linkedinurl  = ""
    facebookurl  = "https://www.facebook.com/kmhinstitute"
    telephone = "+919344674515"
    email     = "academicboard@drkmh.com"
    twitterurl   = ""
    instagramurl = "https://www.instagram.com/kamakshiinstitute/"
    icon = "/icons/android-chrome-512x512.png"
    logo = "/images/kimsr_logo.png"
    logoalt  = "Dr. Kamakshi Institute of Medical Science and Research Logo"
    
  
  [module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.js"
      target = "assets/js/bootstrap.bundle.js"

  [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]

  [menu]
    
    [[menu.main]]
      identifier = "bsc"
      title = "UG Programs"
      url = "/bachelors-of-science"
      weight = 200
    
    [[menu.main]]
      identifier = "msc"
      title = "PG Programs"
      url = "/masters-of-science"
      weight = 300

    [[menu.main]]
      identifier = "diploma"
      title = "Diploma Programs"
      url = "/diploma"
      weight = 400

    [[menu.main]]
      identifier = "dnb"
      title = "DNB Programs"
      url = "/dnb"
      weight = 500
  
  sectionPagesMenu = "main"