BaseURL = "/"
  languageCode = "en-us"
  title = "Dr. Kamakshi Institute of Medical Science and Research"
  theme = "samhugobs5theme"
  relativeURLS = true
  
  [permalinks]
    services = ":title/"

  [params]
    author = "Zigma Marketing"
    description = "Dr. Kamakshi Institute of Medical Science and Research"
    linkedinurl  = ""
    facebookurl  = "https://www.facebook.com/kmhinstitute"
    telephone = "+919344674515"
    email     = "academicboard@drkmh.com"
    twitterurl   = ""
    instagramurl = "https://www.instagram.com/kamakshiinstitute/"
    icon = "/icons/android-chrome-512x512.png"
    logo = "/images/kimsr_logo.png"
    logoalt  = "Dr. Kamakshi Institute of Medical Science and Research Logo"
    
  
  [module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

  [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]

  [menu]
    
    [[menu.main]]
      identifier = "bsc"
      title = "BSc"
      url = "/bachelors-of-science"
      weight = 200
    
    [[menu.main]]
      identifier = "msc"
      title = "MSc"
      url = "/masters-of-science"
      weight = 300

    [[menu.main]]
      identifier = "diploma"
      title = "Diploma"
      url = "/diploma"
      weight = 400

    [[menu.main]]
      identifier = "dnb"
      title = "DNB Programs"
      url = "/dnb"
      weight = 500
  
  sectionPagesMenu = "main"