---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: "\\content\\bachelors-of-science"
  label: Bachelor of Science
  create: all
  match: "**/*"
- type: document
  path: layouts/index.html
  label: Home Page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D
version: 0.81.0
